from .learning_goal import (LEARNING_GOAL_CREATE_EXAMPLE,
                            LEARNING_GOAL_READ_EXAMPLE,
                            LEARNING_GOAL_DETAIL_READ_EXAMPLE,
                            LEARNING_GOAL_WITH_PROGRESS_READ_EXAMPLE,
                            LEARNING_GOAL_UPDATE_EXAMPLE)
from .module import (MODULE_CREATE_EXAMPLE, MODULE_READ_EXAMPLE,
                     MODULE_UPDATE_EXAMPLE)
from .objectives import (OBJECTIVE_CREATE_EXAMPLE, OBJECTIVE_READ_EXAMPLE,
                         OBJECTIVE_UPDATE_EXAMPLE)
from .task import TASK_CREATE_EXAMPLE, TASK_READ_EXAMPLE, TASK_UPDATE_EXAMPLE
from .user import (PASSWORD_UPDATE_EXAMPLE, USER_CREATE_EXAMPLE,
                   USER_READ_EXAMPLE, USER_UPDATE_EXAMPLE)
