from .learning_goal import (LEARNING_GOAL_CREATE_EXAMPLE,
                            LEARNING_GOAL_READ_EXAMPLE,
                            LEARNING_GOAL_DETAIL_READ_EXAMPLE,
                            LEARNING_GOAL_WITH_PROGRESS_READ_EXAMPLE,
                            LEARNING_GOAL_UPDATE_EXAMPLE)
from .module import (MODULE_CREATE_EXAMPLE, MODULE_READ_EXAMPLE,
                     MODULE_UPDATE_EXAMPLE)
from .objectives import (OBJECTIVE_CREATE_EXAMPLE, OBJECTIVE_READ_EXAMPLE,
                         OBJECTIVE_WITH_PROGRESS_READ_EXAMPLE, OBJECTIVE_UPDATE_EXAMPLE)
from .task import TASK_CREATE_EXAMPLE, TASK_READ_EXAMPLE, TASK_UPDATE_EXAMPLE
from .task_note import (TASK_NOTE_CREATE_EXAMPLE, TASK_NOTE_READ_EXAMPLE,
                        TASK_NOTE_UPDATE_EXAMPLE, TASK_NOTE_RESPONSE_EXAMPLE,
                        TASK_NOTE_LIST_RESPONSE_EXAMPLE)
from .task_resource import (TASK_RESOURCE_CREATE_EXAMPLE, TASK_RESOURCE_READ_EXAMPLE,
                            TASK_RESOURCE_UPDATE_EXAMPLE, TASK_RESOURCE_RESPONSE_EXAMPLE,
                            TASK_RESOURCE_LIST_RESPONSE_EXAMPLE)
from .user import (PASSWORD_UPDATE_EXAMPLE, USER_CREATE_EXAMPLE,
                   USER_READ_EXAMPLE, USER_UPDATE_EXAMPLE)

from .roadmap import (ROADMAP_CREATE_EXAMPLE, ROADMAP_READ_EXAMPLE, ROADMAP_UPDATE_EXAMPLE)
from .pomodoro_preferences import (
    POMODORO_PREFERENCES_CREATE_EXAMPLE, 
    POMODORO_PREFERENCES_READ_EXAMPLE,
    POMODORO_CONFIGURATION_CONFIGURED_EXAMPLE,
    POMODORO_CONFIGURATION_NOT_CONFIGURED_EXAMPLE
)
from .self_evaluation import (
    SELF_EVALUATION_CREATE_EXAMPLE,
    SELF_EVALUATION_CREATED_EXAMPLE,
    SELF_EVALUATION_READ_EXAMPLE
)
